UniVerse/urls.py
from django.contrib import admin
from django.urls import path,include
from UniVerse import views
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('',views.home,name="home"),
    path('admin/', admin.site.urls),
 
    path('accounts/', include('accounts.urls')),
    path('notes/', include('notes.urls')),

    path('resources/', include('resources.urls')),

    path('rooms/', include('room.urls')),
    path('connect/', include('connections.urls')),
    path('todolist/',include('todolist.urls')),
    path('dashboard/',views.dashboard,name="dashboard")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/urls.py
from django.urls import path
from .import views

app_name = 'room'
urlpatterns = [
    path('',views.rooms,name='rooms'),
    path('<str:room_name>/',views.room,name='room'),
] 

todolist/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin

app_name = 'todolist'

urlpatterns = [
    path('', views.index, name='index'),
    path('assignments/', views.assignments, name='assignments'),
    path('selfstudy/', views.selfstudy, name='selfstudy'),
    path('create_assignments/', views.create_assignments, name='create_assignments'),
    path('create_selfstudy/', views.create_selfstudy, name='create_selfstudy'),
    path('complete_selfstudy/<uuid:uuid>', views.complete_selfstudy, name='complete_selfstudy'),
    path('complete_assignments/<uuid:uuid>', views.complete_assignments, name='complete_assignments'),
    path('delete_assignments/<uuid:uuid>', views.delete_assignments, name='delete_assignments'),
    path('delete_selfstudy/<uuid:uuid>', views.delete_selfstudy, name='delete_selfstudy'),
]

frontend/models.py
from django.db import models

# Create your models here.

todolist/models.py
from django.db import models
import uuid

class Assignment(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    due_date = models.DateTimeField()
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Selfstudy(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    due_date = models.DateTimeField(null=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

todolist/forms.py
from django import forms
from .models import Selfstudy,Assignment

class selfstudyform(forms.ModelForm):
    class Meta:
        model = Selfstudy
        fields = '__all__'
        
        widgets = {
            "name": forms.TextInput(attrs={'placeholder': 'Enter name here...'}),  
        }

class assignmentsform(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = '__all__'
        
        widgets = {
            "name": forms.TextInput(attrs={'placeholder': 'Enter name here...'}),  
        }

frontend/views.py
from django.shortcuts import render

# Create your views here.

todolist/views.py
from django.shortcuts import render
from .models import Selfstudy, Assignment
from django.shortcuts import redirect
from .forms import selfstudyform, assignmentsform
from datetime import datetime
import uuid
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='accounts:login')
def index(request):
    return render(request, 'todolist/todolist.html')

@login_required(login_url='accounts:login')
def assignments(request):
    assignments= Assignment.objects.all()
    currentTime = datetime.now().replace(tzinfo=None)
    for a in assignments:
        if a.due_date is not None:
            a.is_before_due_date = a.due_date.replace(tzinfo=None) < currentTime
        else:
            a.is_before_due_date = False
    context = {
        'currentTime': currentTime,
        'assignments': assignments
    }
    return render(request, 'todolist/assignments.html',context)

@login_required(login_url='accounts:login')
def selfstudy(request):
    selfstudy=Selfstudy.objects.all()
    currentTime = datetime.now().replace(tzinfo=None)
    for s in selfstudy:
        if s.due_date is not None:
            s.is_before_due_date = s.due_date.replace(tzinfo=None) < currentTime
        else:
            s.is_before_due_date = False

    context = {
        'currentTime': currentTime,
        'selfstudy': selfstudy
    }
    return render(request, 'todolist/selfstudy.html',context)

@login_required(login_url='accounts:login')
def create_assignments(request):
    if request.method == 'POST':
        form = assignmentsform(request.POST)

        if form.is_valid():
            form.save()
            return redirect('todolist:assignments')
    else:
        form = assignmentsform()
    return render(request, 'todolist/assignments.html',{'form': form})

@login_required(login_url='accounts:login')
def create_selfstudy(request):
    if request.method == 'POST':
        form = selfstudyform(request.POST)
        # hi=request.POST['name']
        # print(hi)
        print(form.errors)
        print("hello")
        if form.is_valid():
            print("hello")
            form.save()
            return redirect('todolist:selfstudy')
    else:
        form = selfstudyform()
    return render(request, 'todolist/selfstudy.html', {'form': form})

@login_required(login_url='accounts:login')
def complete_selfstudy(request, uuid):
    selfstudy = Selfstudy.objects.get(uuid=uuid)
    selfstudy.completed=True
    selfstudy.save()
    return redirect('todolist:selfstudy')

@login_required(login_url='accounts:login')
def complete_assignments(request, uuid):
    assignments = Assignment.objects.get(uuid=uuid)
    assignments.completed=True
    assignments.save()
    return redirect('todolist:assignments')

@login_required(login_url='accounts:login')
def delete_selfstudy(request, uuid):
    selfstudy = Selfstudy.objects.get(uuid=uuid)
    selfstudy.delete()
    return redirect('todolist:selfstudy')

@login_required(login_url='accounts:login')
def delete_assignments(request, uuid):
    assignments = Assignment.objects.get(uuid=uuid)
    assignments.delete()
    return redirect('todolist:assignments')

frontend/templates/todolist/assignments.html
{% extends "base/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
<style>
    /* Form Styling */
    .form-container {
        max-width: 500px;
        margin: auto;
        padding: 20px;
        background-color: black;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .form-title {
        text-align: center;
        margin-bottom: 30px;
    }

    /* Table Styling */
    .table-container {
        margin-top: 30px;
    }

    .table thead th {
        background-color: #343a40;
        color: #fff;
    }

    .table tbody tr {
        background-color: #f8f9fa;
    }

    .table tbody tr.green-row {
        background-color: #d4edda;
    }

    .table tbody tr.red-row {
        background-color: #f8d7da;
    }

    .badge {
        cursor: pointer;
    }
    body {
        height: 100vh;
        background-image: url("{% static 'media/assignments3.jpg' %}");
        background-size: cover;
        {% comment %} backdrop-filter: blur(10px); {% endcomment %}
      }
</style>
{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="form-container">
                <h2 class="form-title">Create Assignment</h2>
                <form action="{% url 'todolist:create_assignments' %}" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputName" class="form-label">Name</label>
                        <input type="text" class="form-control" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputDate" class="form-label">Due Date</label>
                        <input type="date" class="form-control" name="due_date" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="container table-container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Serial Number</th>
                        <th>Name</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for s in assignments %}
                        <tr class="{% if s.due_date > s.currentTime %}green-row{% else %}red-row{% endif %}">
                            {% if forloop.first %}
                                <td>1</td>
                            {% else %}
                                <td>{{ forloop.counter }}</td>
                            {% endif %}
                            <td>{{ s.name }}</td>
                            <td>{{ s.due_date }}</td>
                            <td>
                                {% if s.completed %}
                                    <span class="badge bg-success">Completed</span>
                                {% else %}
                                    <span class="badge bg-danger">Pending</span>
                                {% endif %}
                            </td>
                            <td>
                                {% if not s.completed %}
                                    <a class="badge bg-primary text-light" href="{% url 'todolist:complete_assignments' s.uuid %}">Complete</a>
                                {% endif %}
                                <a class="badge bg-danger text-light" href="{% url 'todolist:delete_assignments' s.uuid %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

frontend/templates/todolist/selfstudy.html
{% extends "base/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
<style>
    /* Form Styling */
    .form-container {
        max-width: 500px;
        margin: auto;
        padding: 20px;
        background-color: black;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .form-title {
        text-align: center;
        margin-bottom: 30px;
    }

    /* Table Styling */
    .table-container {
        margin-top: 30px;
    }

    .table thead th {
        background-color: #343a40;
        color: #fff;
    }

    .table tbody tr {
        background-color: #f8f9fa;
    }

    .table tbody tr.green-row {
        background-color: #d4edda;
    }

    .table tbody tr.red-row {
        background-color: #f8d7da;
    }

    .badge {
        cursor: pointer;
    
    }
    .custom-shadow {
        box-shadow: 25 25 25px rgba(250, 234, 5, 0.5); /* Change the color by adjusting the RGBA values */
    }
    body {
        height: 100vh;
        background-image: url("{% static 'media/selfstudy.jpg' %}");
        background-size: cover;
        /* backdrop-filter: blur(10px); */
      }
</style>
{% endblock %}

{% block content %}
<div class="container my-5 ">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="form-container custom-shadow">
                <h2 class="form-title">Things to remember</h2>
                <form action="{% url 'todolist:create_selfstudy' %}" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputName" class="form-label">Name</label>
                        <input type="text" class="form-control" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputDate" class="form-label">By</label>
                        <input type="date" class="form-control" name="due_date" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="container table-container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Serial Number</th>
                        <th>Name</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for s in selfstudy %}
                        <tr class="{% if s.due_date > s.currentTime %}green-row{% else %}red-row{% endif %}">
                            {% if forloop.first %}
                                <td>1</td>
                            {% else %}
                                <td>{{ forloop.counter }}</td>
                            {% endif %}
                            <td>{{ s.name }}</td>
                            <td>{{ s.due_date }}</td>
                            <td>
                                {% if s.completed %}
                                    <span class="badge bg-success">Completed</span>
                                {% else %}
                                    <span class="badge bg-danger">Pending</span>
                                {% endif %}
                            </td>
                            <td>
                                {% if not s.completed %}
                                    <a class="badge bg-primary text-light" href="{% url 'todolist:complete_selfstudy' s.uuid %}">Complete</a>
                                {% endif %}
                                <a class="badge bg-danger text-light" href="{% url 'todolist:delete_selfstudy' s.uuid %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

frontend/templates/todolist/todolist.html
{% extends "base/base.html" %}
{% load static %}
{% block head%}
  <style>
    .black{
      color: black;
    }

    body {
      height: 100vh;
      background-image: url("{% static 'media/todolist2.jpg' %}");
      background-size: cover;
      background-position: center;
      backdrop-filter: blur(10px);
    }
  </style>
{% endblock %}
{% block content %}
<div class="container justify-content-center">
<div class="px-4 py-5 my-5 text-center">
    <img class="d-block mx-auto mb-4" src="{% static "media/todolist.jpg" %}" alt="" width="72" height="57">
    <div class="">
    <h1 class="display-5 fw-bold text-light">Never forget your Assignments now</h1>
  </div>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4"></p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a href="{% url 'todolist:assignments' %}">
          <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Assignments</button>
        </a>
        <a href="{% url 'todolist:selfstudy' %}">
          <button type="button" class="btn btn-primary btn-lg px-4">Things to remember</button>
        </a>
      </div>
    </div>
  </div>
</div>
  {% endblock%}